- alias: Start HomeKit
  trigger:
  - platform: event
    event_type: zwave.network_ready
  - platform: event
    event_type: zwave.network_complete
  action:
  - service: homekit.start
  id: 71f013a0065d4d7eb28363dd4d2ad19c
- id: '1584906173138'
  alias: HASS update available
  description: Notify Knut that a HASS update is available
  trigger:
  - entity_id: binary_sensor.updater
    from: '''off'''
    platform: state
    to: '''on'''
  condition: []
  action:
  - data_template:
      title: Home Assistant-oppdatering
      message: Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version')
        }} er nå tilgjengelig.
      data:
        attachment:
          url: '{{ state_attr(''binary_sensor.updater'', ''release_notes'') }}'
    service: notify.mobile_app_knut_iphone
- id: '1591439705611'
  alias: Tablet cycle power
  description: ''
  trigger:
  - above: '0'
    below: '100'
    entity_id: sensor.tablet_rest
    platform: numeric_state
  condition: []
  action:
  - data: {}
    entity_id: switch.tablet_power_switch
    service: switch.turn_off
  - delay: 00:00:01
  - data: {}
    entity_id: switch.tablet_power_switch
    service: switch.turn_on
- id: '1603953978571'
  alias: 'Tablet: Periodic power on'
  description: ''
  trigger:
  - platform: time_pattern
    minutes: /15
  condition: []
  action:
  - type: turn_on
    device_id: 3676dd2b459549c5ae06f4b9cfc667c4
    entity_id: switch.tablet_power_switch
    domain: switch
  mode: single
- id: '1609146235387'
  alias: 'Bad: Taklys'
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      no_motion_wait: '660'
      motion_entity: binary_sensor.bathroom_movement
      light_target:
        entity_id:
        - light.taklys_bad
