- platform: template
  sensors:
    bathroom_movement:
      device_class: motion
      friendly_name: Bevegelse bad
      value_template: "{{ is_state('sensor.bathroom_multisensor_motion', '8') }}"
    house_not_night_mode:
      friendly_name: House is not in night mode
      value_template: "{{ not is_state('input_select.house_mode', 'Natt')}}"