homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 140
  unit_system: metric
  time_zone: Europe/Oslo
  customize: !include customize.yaml  
  customize_glob: !include customize_glob.yaml
  auth_providers:
   - type: homeassistant
   - type: legacy_api_password
    

config:
conversation:
discovery:
frontend:
history:
logbook:
map:
sun:
updater:

logger:
    default: info
    logs:
        custom_components.volkswagen_carnet: debug


http:
  api_password: !secret http_password
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1


############################################
# RFXtrx configuration
############################################
rfxtrx:
  device: /dev/ttyUSB0


############################################
# Zwave configuration
############################################

zwave:
  usb_path: /dev/ttyACM0
  polling_interval: 45000
  device_config:
    
    switch.bathroom_ceiling_light:
      polling_intensity: 1
      refresh_value: True
    
    switch.bathroom_fan:
      polling_intensity: 1
      refresh_value: True
      

mqtt:
  broker: core-mosquitto
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  client_id: home-assistant
  protocol: 3.1
  birth_message:
    topic: "tele/hass1/LWT"
    payload: "Online"
    qos: 1
    retain: false
  will_message:
    topic: "tele/hass1/LWT"
    payload: "Offline"
    qos: 1
    retain: false
 
# influxdb:
#   host: 172.17.0.5
#   username: !secret influxdb_username
#   password: !secret influxdb_password
#   database: home_assistant
#   exclude:
#     domains:
#       - automation
#       - group
#       - camera
#       - device_tracker
#       - input_select
#       - light
#       - media_player
#       - scene
#       - script
#       - zone
#   tags:
#     source: hass


# Text to speech
tts:
  - platform: google
    language: 'no'


# Trådfri
tradfri:
  host: !secret tradfri_host
  allow_tradfri_groups: False


# Cloud
cloud:


############################################
# Enable IDE in main menu
############################################
panel_iframe:
  ide:
    title: IDE
    icon: mdi:code-braces
    url: !secret ide_url
  grafana:
    title: Grafana
    icon: mdi:chart-timeline
    url: !secret grafana_url


############################################
# Device Trackers
############################################
device_tracker:
  # - platform: asuswrt
  #   host: !secret router_ip
  #   protocol: telnet
  #   username: admin
  #   password: !secret router_password
    
  - platform: unifi
    host: localhost
    port: 8443
    username: !secret unifi_username
    password: !secret unifi_password

  - platform: owntracks_http
    max_gps_accuracy: 200


############################################
# Notifications
############################################

notify:
  - platform: ios
    name: knut
    target: !secret knut_ios_push_key
  - platform: ios
    name: simon
    target: !secret simon_ios_push_key

############################################
# Volkswagen Car-net
############################################
volkswagen_carnet:
  username: !secret vw_username
  password: !secret vw_password
  update_interval:
    minutes: 5


############################################
# Includes
############################################

automation: !include_dir_merge_list automation
binary_sensor: !include binary_sensors.yaml
camera: !include cameras.yaml
group: !include groups.yaml
homekit: !include homekit.yaml
input_boolean: !include_dir_merge_named input_boolean
input_select: !include_dir_merge_named input_select
light: !include lights.yaml
scene: !include_dir_merge_list scenes
sensor: !include_dir_merge_list sensors
script: !include scripts.yaml
timer: !include timers.yaml
switch: !include_dir_merge_list switches
zone: !include_dir_merge_list zone
  
