homeassistant:
  auth_providers:
   - type: homeassistant
  packages: !include_dir_named packages

config:
conversation:

discovery:
  ignore:
    - igd

frontend:
  themes: !include_dir_merge_named themes

history:
logbook:
map:
sun:
system_health:

updater:
webhook:

lovelace:
  mode: storage

recorder:
  db_url: !secret mariadb_conn

logger:
  default: error
  logs:
    homeassistant.components.rfxtrx: debug
    custom_components.volkswagencarnet: error

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1

mobile_app:
ios:

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state


############################################
# Includes
############################################
automation: !include automations.yaml
camera: !include cameras.yaml
homekit: !include homekit.yaml
light: !include lights.yaml
scene: !include_dir_merge_list scenes
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
zone: !include_dir_merge_list zone

browser_mod:
  prefix: "browser_"
  devices:
    4efee875-9fa0dc82:
      name: knut_iphone_app
    b6905551-b155375f:
      name: knut_laptop_chrome
    8345a03b-dab7ee22:
      name: tablet


############################################
# RFXtrx configuration
############################################
rfxtrx:
  device: /dev/ttyUSB1


############################################ 
# Text to speech
############################################
tts:
  - platform: google_translate
    service_name: google_say
    language: 'no'


############################################
# Device Trackers
############################################
device_tracker:


############################################
# Volkswagen Car-net
############################################
volkswagencarnet:
  username: !secret vw_username
  password: !secret vw_password


############################################
# Tibber
############################################
tibber:
  access_token: !secret tibber_access_token