homeassistant:
  auth_providers:
   - type: homeassistant
  packages: !include_dir_named packages

config:
conversation:

discovery:
  ignore:
    - igd

frontend:
  themes: !include_dir_merge_named themes

history:
logbook:
map:
sun:
system_health:

updater:
webhook:

lovelace:
  mode: storage

recorder:
  db_url: !secret mariadb_conn

logger:
  default: warning
  logs:
    homeassistant.components.rfxtrx: debug
    custom_components.volkswagencarnet: error

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1

mobile_app:
ios:

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret influxdb_username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state


############################################
# Includes
############################################
automation: !include automations.yaml
camera: !include cameras.yaml
homekit: !include homekit.yaml
light: !include lights.yaml
scene: !include_dir_merge_list scenes
sensor: !include_dir_merge_list sensors
zone: !include_dir_merge_list zone

browser_mod:
  prefix: "browser_"
  devices:
    4efee875-9fa0dc82:
      name: knut_iphone_app
    b6905551-b155375f:
      name: knut_laptop_chrome
    8345a03b-dab7ee22:
      name: tablet


############################################
# RFXtrx configuration
############################################
rfxtrx:
  device: /dev/ttyUSB1
  devices:
    # Valperom, Viking Thermometer 1
    085007d9960000e979:
    # Ute kjellertrapp, Viking Thermometer 3
    0850070f9f0000e879:
    #Ute inngang, Oregon Scientific
    08500220c201012569:

    # Tablet power switch
    0b11000512bc0cfe08010f70:
      fire_event: True

    # basement_office_heater
    0b11000544bc0cfe08010f70:
      fire_event: True

    # T10 thermometer basement office
    0a5209114a0000952d0179:

    # Nattbordslampe
    0710030e41020250:
      device_class: light
      fire_event: True

    # Temperatur stue, Viking Thermometer 2
    08500704970000ed79:

    # Temperatur vaskerom
    0a520950190000a3320179:
    
    # Kjeller gulvlampe
    0710030e41030150:
      device_class: light
      fire_event: True

    # Kjeller lampett 1
    0b11006d01ce6f6e01010f70:
      device_class: light
      fire_event: True

    # Kjeller lampett 2
    0b11007501ce6f6e02010f70:
      device_class: light
      fire_event: True
      
    # Kjeller lampett 3
    0b11007601ce6f6e03010f70:
      device_class: light
      fire_event: True


############################################ 
# Text to speech
############################################
tts:
  - platform: google_translate
    service_name: google_say
    language: 'no'


############################################
# Device Trackers
############################################
device_tracker:


############################################
# Tibber
############################################
tibber:
  access_token: !secret tibber_access_token