homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_lon
  elevation: 140
  unit_system: metric
  time_zone: Europe/Oslo
  customize: !include customize.yaml  
  customize_glob: !include customize_glob.yaml
  auth_providers:
   - type: homeassistant

cloud:
config:
conversation:
discovery:
frontend:
history:
logbook:
map:
sun:
system_health:
updater:
webhook:

logger:
    default: info

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1


############################################
# Includes
############################################
automation: !include_dir_merge_list automation
binary_sensor: !include binary_sensors.yaml
camera: !include cameras.yaml
group: !include groups.yaml
homekit: !include homekit.yaml
input_boolean: !include_dir_merge_named input_boolean
input_select: !include_dir_merge_named input_select
light: !include lights.yaml
scene: !include_dir_merge_list scenes
sensor: !include_dir_merge_list sensors
script: !include scripts.yaml
timer: !include timers.yaml
switch: !include_dir_merge_list switches
zone: !include_dir_merge_list zone


############################################
# RFXtrx configuration
############################################
rfxtrx:
  device: /dev/ttyUSB1


############################################ 
# Text to speech
############################################
tts:
  - platform: google
    language: 'no'


############################################
# Zigbee2mqtt network map
############################################
zigbee2mqtt_networkmap:


############################################
# Enable ipanels in main menu
############################################
panel_iframe:
  ide:
    title: IDE
    icon: mdi:code-braces
    url: !secret ide_url
  grafana:
    title: Grafana
    icon: mdi:chart-timeline
    url: !secret grafana_url
  networkmap:
   title: 'Zigbee Map'
   url: '/local/zigbee2mqtt_networkmap/map.html'
   icon: 'mdi:graphql'


############################################
# Device Trackers
############################################
device_tracker:
  - platform: unifi
    host: a0d7b954-unifi
    port: 8443
    username: !secret unifi_username
    password: !secret unifi_password
    verify_ssl: false
    ssid_filter:
      - 'BazingaNet'


############################################
# Notifications
############################################
notify:
  - platform: ios
    name: knut
    target: !secret knut_ios_push_key
  - platform: ios
    name: simon
    target: !secret simon_ios_push_key


############################################
# Volkswagen Car-net
############################################
volkswagencarnet:
  username: !secret vw_username
  password: !secret vw_password
  update_interval:
    minutes: 5

