
- platform: group
  name: Alt lys kjeller
  entities:
    - light.kjeller_gulvlampe
    - light.kjeller_lampett_1
    - light.kjeller_lampett_2
    - light.kjeller_lampett_3
  
    
- platform: group
  name: Stue
  entities:
    - light.trapp_1
    - light.trapp_2
    - light.trapp_3
    - light.trapp_4
    - light.trapp_5
    - light.trapp_6
    - light.trapp_7
    - light.trapp_8
    - light.horus_1
    - light.horus_2
    - light.horus_3
    - light.horus_4
    - light.horus_5
    - light.horus_6
    - light.horus_7
    - light.horus_8
    - light.horus_9
    - light.horus_10
    - light.hund_1
    - light.hund_2
    - light.hund_3
    - light.hund_4

- platform: group
  name: "Trapp"
  entities:
    - light.trapp_1
    - light.trapp_2
    - light.trapp_3
    - light.trapp_4
    - light.trapp_5
    - light.trapp_6
    - light.trapp_7
    - light.trapp_8

- platform: group
  name: "Hund"
  entities:
    - light.hund_1
    - light.hund_2
    - light.hund_3
    - light.hund_4

- platform: group
  name: "Spisebord"
  entities:
    - light.horus_6
    - light.horus_7
    - light.horus_8
    - light.horus_9

- platform: group
  name: "Valpehage"
  entities:
    - light.trapp_6
    - light.trapp_7
    - light.trapp_8
    - light.horus_5


- platform: mqtt
  name: "Garage center"
  state_topic: "stat/garage/POWER1"
  command_topic: "cmnd/garage/POWER1"
  availability_topic: "tele/garage/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  
- platform: mqtt
  name: "Garage left"
  state_topic: "stat/garage/POWER2"
  command_topic: "cmnd/garage/POWER2"
  availability_topic: "tele/garage/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  
- platform: mqtt
  name: "Garage right"
  state_topic: "stat/garage/POWER3"
  command_topic: "cmnd/garage/POWER3"
  availability_topic: "tele/garage/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false