- platform: group
  name: Stuelys
  entities:
    - light.horus_1
    - light.horus_2
    - light.horus_3
    - light.horus_4
    - light.horus_5
    - light.horus_6
    - light.horus_7
    - light.horus_8
    - light.horus_9
    - light.horus_10
    - light.trapp_1
    - light.trapp_2
    - light.trapp_3
    - light.trapp_4
    - light.trapp_5
    - light.trapp_6
    - light.trapp_7
    - light.trapp_8
    - light.hund_1
    - light.hund_2
    - light.hund_3
    - light.hund_4
    
- platform: group
  name: Horus_
  entities:
    - light.horus_1
    - light.horus_2
    - light.horus_3
    - light.horus_4
    - light.horus_5
    - light.horus_6
    - light.horus_7
    - light.horus_8
    - light.horus_9
    - light.horus_10
    
- platform: group
  name: Valpehage
  entities:
    - light.trapp_7
    - light.trapp_8
    - light.horus_5
    - light.horus_6
    

- platform: group    
  name: Trapp_
  entities:
    - light.trapp_1
    - light.trapp_2
    - light.trapp_3
    - light.trapp_4
    - light.trapp_5
    - light.trapp_6
    - light.trapp_7
    - light.trapp_8
    
- platform: group
  name: Hundehjørnet_
  entities:
    - light.hund_1
    - light.hund_2
    - light.hund_3
    - light.hund_4
    
- platform: group
  name: Spisebord
  entities:
    - light.horus_8
    - light.horus_9
    - light.horus_10
    
- platform: group
  name: Nattlys
  entities:
    - light.inngang
    - light.horus_3
    - light.trapp_1
    - light.hund_2
    
- platform: group
  name: Bedroom
  entities:
    - light.soverom_1
    - light.soverom_2

- platform: group
  name: Valperom
  entities:
    - light.valperom_1
    - light.valperom_2
    - light.valperom_3


- platform: rfxtrx
  #automatic_add: true
  devices:
    0710030e41020150:
      name: Bed light
      fire_event: true
    0710030e41030150:
      name: Basement
      fire_event: true

- platform: mqtt
  name: "Garage center"
  state_topic: "stat/garage/POWER1"
  command_topic: "cmnd/garage/POWER1"
  availability_topic: "tele/garage/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  
- platform: mqtt
  name: "Garage left"
  state_topic: "stat/garage/POWER2"
  command_topic: "cmnd/garage/POWER2"
  availability_topic: "tele/garage/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  
- platform: mqtt
  name: "Garage right"
  state_topic: "stat/garage/POWER3"
  command_topic: "cmnd/garage/POWER3"
  availability_topic: "tele/garage/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  
- platform: mqtt
  name: "Garage outside"
  state_topic: "stat/garage/POWER4"
  command_topic: "cmnd/garage/POWER4"
  availability_topic: "tele/garage/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false