- platform: mqtt
  name: "Garage center"
  state_topic: "stat/garage/POWER1"
  command_topic: "cmnd/garage/POWER1"
  availability_topic: "tele/garage/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  
- platform: mqtt
  name: "Garage left"
  state_topic: "stat/garage/POWER2"
  command_topic: "cmnd/garage/POWER2"
  availability_topic: "tele/garage/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  
- platform: mqtt
  name: "Garage right"
  state_topic: "stat/garage/POWER3"
  command_topic: "cmnd/garage/POWER3"
  availability_topic: "tele/garage/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false