- platform: group
  name: Stuelys
  entities:
    - light.horus_1
    - light.horus_2
    - light.horus_3
    - light.horus_4
    - light.horus_5
    - light.horus_6
    - light.horus_7
    - light.horus_8
    - light.horus_9
    - light.horus_10
    - light.trapp_1
    - light.trapp_2
    - light.trapp_3
    - light.trapp_4
    - light.trapp_5
    - light.trapp_6
    - light.trapp_7
    - light.trapp_8
    - light.hund_1
    - light.hund_2
    - light.hund_3
    - light.hund_4
    
- platform: group
  name: Horus_
  entities:
    - light.horus_1
    - light.horus_2
    - light.horus_3
    - light.horus_4
    - light.horus_5
    - light.horus_6
    - light.horus_7
    - light.horus_8
    - light.horus_9
    - light.horus_10

- platform: group    
  name: Trapp_
  entities:
    - light.trapp_1
    - light.trapp_2
    - light.trapp_3
    - light.trapp_4
    - light.trapp_5
    - light.trapp_6
    - light.trapp_7
    - light.trapp_8
    
- platform: group
  name: Hundehjørnet_
  entities:
    - light.hund_1
    - light.hund_2
    - light.hund_3
    - light.hund_4
    
- platform: group
  name: Spisebord
  entities:
    - light.horus_8
    - light.horus_9
    - light.horus_10
    
- platform: group
  name: Nattlys
  entities:
    - light.inngang
    - light.horus_3
    - light.trapp_1
    - light.hund_2

- platform: rfxtrx
  #automatic_add: true
  devices:
    0710030e41020150:
      name: Nattbordslampe
      fire_event: true
