
- platform: group
  name: Alt lys kjeller
  entities:
    - light.kjeller_gulvlampe
    - light.kjeller_lampett_1
    - light.kjeller_lampett_2
    - light.kjeller_lampett_3

- platform: group
  name: "Taklys soverom"
  entities:
    - light.soverom_tak_1
    - light.soverom_tak_2

- platform: rfxtrx
  #automatic_add: true
  devices:
    0710030e41020150:
      name: Nattbordslampe
      fire_event: true
    0710030e41030150:
      name: Kjeller gulvlampe
      fire_event: true
    0b11006d01ce6f6e01010f70:
      name: Kjeller lampett 1
      fire_event: true
    0b11007501ce6f6e02010f70:
      name: Kjeller lampett 2
      fire_event: true
    0b11007601ce6f6e03010f70:
      name: Kjeller lampett 3
      fire_event: true

- platform: mqtt
  name: "Garage center"
  state_topic: "stat/garage/POWER1"
  command_topic: "cmnd/garage/POWER1"
  availability_topic: "tele/garage/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  
- platform: mqtt
  name: "Garage left"
  state_topic: "stat/garage/POWER2"
  command_topic: "cmnd/garage/POWER2"
  availability_topic: "tele/garage/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  
- platform: mqtt
  name: "Garage right"
  state_topic: "stat/garage/POWER3"
  command_topic: "cmnd/garage/POWER3"
  availability_topic: "tele/garage/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  
- platform: mqtt
  name: "Garage outside"
  state_topic: "stat/garage/POWER4"
  command_topic: "cmnd/garage/POWER4"
  availability_topic: "tele/garage/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
  
- platform: mqtt
  schema: json
  name: "Stue"
  command_topic: "zigbee2mqtt/lys_stue/set"
  state_topic: "zigbee2mqtt/lys_stue/set"
  color_temp: true
  brightness: true
  
- platform: mqtt
  schema: json
  name: "Hund"
  command_topic: "zigbee2mqtt/lys_hund/set"
  state_topic: "zigbee2mqtt/lys_hund/set"
  color_temp: true
  brightness: true
  
- platform: mqtt
  schema: json
  name: "Trapp"
  command_topic: "zigbee2mqtt/lys_trapp/set"
  state_topic: "zigbee2mqtt/lys_trapp/set"
  color_temp: true
  brightness: true
  
- platform: mqtt
  schema: json
  name: "Horus"
  command_topic: "zigbee2mqtt/lys_horus/set"
  state_topic: "zigbee2mqtt/lys_horus/set"
  color_temp: true
  brightness: true
  
- platform: mqtt
  schema: json
  name: "Valpehage"
  command_topic: "zigbee2mqtt/lys_valpehage/set"
  state_topic: "zigbee2mqtt/lys_valpehage/set"
  color_temp: true
  brightness: true
  
- platform: mqtt
  schema: json
  name: "Spisebord"
  command_topic: "zigbee2mqtt/lys_spisebord/set"
  state_topic: "zigbee2mqtt/lys_spisebord/set"
  color_temp: true
  brightness: true
  
- platform: mqtt
  schema: json
  name: "Valperom"
  command_topic: "zigbee2mqtt/lys_valperom/set"
  state_topic: "zigbee2mqtt/lys_valperom/set"
  color_temp: true
  brightness: true