custom_header:
  compact_mode: true
  exceptions:
    - conditions:
        user_agent: "HUAWEI"
        user: Tablet
      config:
        default_tab: tablet
        voice_hide: true
        options_hide: true
        menu_hide: true
        header_css: "background: #384048;"
resources:
  - type: module
    url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
  - type: module
    url: /community_plugin/mini-media-player/mini-media-player-bundle.js
  - type: module
    url: /community_plugin/button-card/button-card.js
  - url: /community_plugin/custom-header/custom-header.js
    type: module
  - type: module
    url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
  - url: /community_plugin/lovelace-multiple-entity-row/multiple-entity-row.js
    type: module
  - url: /community_plugin/lovelace-card-mod/card-mod.js
    type: module
  
title: Villa Bazinga
views:
  - !include lovelace/tablet.yaml
  - !include lovelace/rooms.yaml
  - !include lovelace/energy_nv15.yaml
  - !include lovelace/energy_nv17.yaml