title: Villa Bazinga

resources:
  - url: /local/monster-card.js
    type: js

views:
### Home
  - title: Home
    cards:
      - type: entities
        title: Valperom
        show_header_toggle: false
        entities:
          - scene.valpekasse
          - sensor.valperom_temperature
          - light.valperom

      
      - type: entities
        title: Bad
        show_header_toggle: false
        entities:
          - sensor.bathroom_multisensor_temperature
          - sensor.bathroom_multisensor_relative_humidity
          - switch.bathroom_ceiling_light
          
      - type: entities
        title: Annet
        show_header_toggle: false
        entities:
          - light.taklys_gang
          - light.inngang


### Stue
      - type: entities
        title: Stue
        show_header_toggle: false
        entities:
          - sensor.stue_temperature
          - light.stue
          - light.trapp
          - light.horus
          - light.spisebord
          - light.valpehage
      - type: entities
        title: Kjøkken
        show_header_toggle: false
        entities:
          - light.taklys_kjokken
          - light.kjokkenskap

### Vær
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - sensor.ute_kjellertrapp_temperature
              - sensor.ute_inngang_temperature
          - type: picture-entity
            entity: camera.meteogram
            show_info: false
          
### Garasje          
      - type: entities
        title: Garasje
        show_header_toggle: false
        entities:
          - light.garage_outside
          - light.garage_center

#################
# SYSTEM
#################

  - title: System
    cards:
      - type: entities
        title: Zigbee2mqtt
        show_header_toggle: false
        entities:
          - input_boolean.zigbee_permit_join
          - timer.zigbee_permit_join
          - sensor.bridge_state
          
          
#################
# Ute og bil
#################
  - icon: mdi:car
    title: Bil
    show_header_toggle: False
    cards:
      - type: custom:monster-card
        card:
          type: entities
          title: El-Bazinga
        filter:
          include:
            - entity_id: lock.wv*
            - entity_id: binary_sensor.wv*
            - entity_id: sensor.wv*
            - entity_id: switch.wv*
            - entity_id: device_tracker.wv*