- platform: rfxtrx
  automatic_add: True
  devices:
    08500220c201012569: # Oregon Scientific thermometer
      name: Ute inngang
    085007d9960000e979: # Viking Thermometer 1
      name: Valperom
    08500704970000ed79: # Viking Thermometer 2
      name: Stue
    0850070f9f0000e879: # Viking Thermometer 3
      name: Ute kjellertrapp
    0a52090a860000d8350179:
      name: T10