- platform: template
  sensors:

  # Tibbersensorer strømpris NV15
    tibber_max_price:
      friendly_name: "Maxpris"
      unit_of_measurement: "NOK/kWh"
      value_template: "{{ state_attr('sensor.electricity_price_nv15', 'max_price') }}"
      icon_template: mdi:currency-usd

    tibber_avg_price:
      friendly_name: "Gjennomsnittspris"
      unit_of_measurement: "NOK/kWh"
      value_template: "{{ state_attr('sensor.electricity_price_nv15', 'avg_price') }}"
      icon_template: mdi:currency-usd

    tibber_min_price:
      friendly_name: "Minimumspris"
      unit_of_measurement: "NOK/kWh"
      value_template: "{{ state_attr('sensor.electricity_price_nv15', 'min_price') }}"
      icon_template: mdi:currency-usd

    tibber_off_peak_1_price:
      friendly_name: "Off peak 1"
      unit_of_measurement: "NOK/kWh"
      value_template: "{{ state_attr('sensor.electricity_price_nv15', 'off_peak_1') }}"
      icon_template: mdi:currency-usd

    tibber_off_peak_2_price:
      friendly_name: "Off peak 2"
      unit_of_measurement: "NOK/kWh"
      value_template: "{{ state_attr('sensor.electricity_price_nv15', 'off_peak_2') }}"
      icon_template: mdi:currency-usd

    tibber_peak_price:
      friendly_name: "Peak"
      unit_of_measurement: "NOK/kWh"
      value_template: "{{ state_attr('sensor.electricity_price_nv15', 'peak') }}"
      icon_template: mdi:currency-usd

    tibber_pricelevel:
      friendly_name: "Prisnivå"
      unit_of_measurement: "state"
      value_template: "{{ state_attr('sensor.electricity_price_nv15', 'price_level') }}"
      icon_template: mdi:currency-usd

    ##############################
    ##### Consumption sensors NV15
    ##############################
    nv15_estimated_annual_consumption:
      friendly_name: "Estimert årsforbruk"
      unit_of_measurement: "kWh"
      value_template: "{{ state_attr('sensor.electricity_price_nv15', 'estimated_annual_consumption') }}"
      icon_template: mdi:power-socket-de

    nv15_meter_reading:
      friendly_name: Målerstand NV15
      unit_of_measurement: kWh
      value_template: "{{ state_attr('sensor.real_time_consumption_norumvegen_15', 'lastMeterConsumption')}}"
      icon_template: mdi:counter

    nv15_timestamp:
      friendly_name: Sist oppdatert
      unit_of_measurement: time
      value_template: "{{ state_attr('sensor.real_time_consumption_norumvegen_15', 'timestamp')}}"

    nv15_accumulated_consumption:
      friendly_name: Akkumulert forbruk
      unit_of_measurement: kWh
      value_template: "{{ state_attr('sensor.real_time_consumption_norumvegen_15', 'accumulatedConsumption')}}"
      icon_template: mdi:currency-usd

    nv15_accumulated_cost:
      friendly_name: Akkumulert kostnad
      unit_of_measurement: kr
      value_template: "{{ state_attr('sensor.real_time_consumption_norumvegen_15', 'accumulatedCost')}}"
      icon_template: mdi:currency-usd

    nv15_power:
      friendly_name: Effekt
      unit_of_measurement: W
      value_template: "{{ states('sensor.real_time_consumption_norumvegen_15') }}"
      icon_template: mdi:power-socket-de

    nv15_min_power:
      friendly_name: Min effekt
      unit_of_measurement: W
      value_template: "{{ state_attr('sensor.real_time_consumption_norumvegen_15', 'minPower')}}"
      icon_template: mdi:power-socket-de

    nv15_avg_power:
      friendly_name: Avg effekt
      unit_of_measurement: W
      value_template: "{{ state_attr('sensor.real_time_consumption_norumvegen_15', 'averagePower')}}"
      icon_template: mdi:power-socket-de

    nv15_max_power:
      friendly_name: Max effekt
      unit_of_measurement: W
      value_template: "{{ state_attr('sensor.real_time_consumption_norumvegen_15', 'maxPower')}}"
      icon_template: mdi:power-socket-de

    nv15_u_l1:
      friendly_name: Spenning L1
      unit_of_measurement: V
      value_template: "{{ state_attr('sensor.real_time_consumption_norumvegen_15', 'voltagePhase1')}}"
      icon_template: mdi:flash

    nv15_u_l2:
      friendly_name: Spenning L2
      unit_of_measurement: V
      value_template: "{{ state_attr('sensor.real_time_consumption_norumvegen_15', 'voltagePhase2')}}"
      icon_template: mdi:flash

    nv15_u_l3:
      friendly_name: Spenning L3
      unit_of_measurement: V
      value_template: "{{ state_attr('sensor.real_time_consumption_norumvegen_15', 'voltagePhase3')}}"
      icon_template: mdi:flash

    nv15_a_l1:
      friendly_name: Strøm L1
      unit_of_measurement: A
      value_template: "{{ state_attr('sensor.real_time_consumption_norumvegen_15', 'currentPhase1')}}"
      icon_template: mdi:current-ac

    nv15_a_l2:
      friendly_name: Strøm L2
      unit_of_measurement: A
      value_template: "{{ state_attr('sensor.real_time_consumption_norumvegen_15', 'currentPhase2')}}"
      icon_template: mdi:current-ac

    nv15_a_l3:
      friendly_name: Strøm L3
      unit_of_measurement: A
      value_template: "{{ state_attr('sensor.real_time_consumption_norumvegen_15', 'currentPhase3')}}"
      icon_template: mdi:current-ac

    
    ##############################
    ##### Consumption sensors NV17
    ##############################
    nv17_estimated_annual_consumption:
      friendly_name: "Estimert årsforbruk"
      unit_of_measurement: "kWh"
      value_template: "{{ state_attr('sensor.electricity_price_nv17', 'estimated_annual_consumption') }}"
      icon_template: mdi:power-socket-de

    nv17_meter_reading:
      friendly_name: Målerstand nv17
      unit_of_measurement: kWh
      value_template: "{{ state_attr('sensor.real_time_consumption_norumvegen_17', 'lastMeterConsumption')}}"
      icon_template: mdi:counter

    nv17_timestamp:
      friendly_name: Sist oppdatert
      unit_of_measurement: time
      value_template: "{{ state_attr('sensor.real_time_consumption_norumvegen_17', 'timestamp')}}"

    nv17_accumulated_consumption:
      friendly_name: Akkumulert forbruk
      unit_of_measurement: kWh
      value_template: "{{ state_attr('sensor.real_time_consumption_norumvegen_17', 'accumulatedConsumption')}}"
      icon_template: mdi:currency-usd

    nv17_accumulated_cost:
      friendly_name: Akkumulert kostnad
      unit_of_measurement: kr
      value_template: "{{ state_attr('sensor.real_time_consumption_norumvegen_17', 'accumulatedCost')}}"
      icon_template: mdi:currency-usd

    nv17_power:
      friendly_name: Effekt
      unit_of_measurement: W
      value_template: "{{ states('sensor.real_time_consumption_norumvegen_17') }}"
      icon_template: mdi:power-socket-de

    nv17_min_power:
      friendly_name: Min effekt
      unit_of_measurement: W
      value_template: "{{ state_attr('sensor.real_time_consumption_norumvegen_17', 'minPower')}}"
      icon_template: mdi:power-socket-de

    nv17_avg_power:
      friendly_name: Avg effekt
      unit_of_measurement: W
      value_template: "{{ state_attr('sensor.real_time_consumption_norumvegen_17', 'averagePower')}}"
      icon_template: mdi:power-socket-de

    nv17_max_power:
      friendly_name: Max effekt
      unit_of_measurement: W
      value_template: "{{ state_attr('sensor.real_time_consumption_norumvegen_17', 'maxPower')}}"
      icon_template: mdi:power-socket-de

    nv17_u_l1:
      friendly_name: Spenning L1
      unit_of_measurement: V
      value_template: "{{ state_attr('sensor.real_time_consumption_norumvegen_17', 'voltagePhase1')}}"
      icon_template: mdi:flash

    nv17_u_l2:
      friendly_name: Spenning L2
      unit_of_measurement: V
      value_template: "{{ state_attr('sensor.real_time_consumption_norumvegen_17', 'voltagePhase2')}}"
      icon_template: mdi:flash

    nv17_u_l3:
      friendly_name: Spenning L3
      unit_of_measurement: V
      value_template: "{{ state_attr('sensor.real_time_consumption_norumvegen_17', 'voltagePhase3')}}"
      icon_template: mdi:flash

    nv17_a_l1:
      friendly_name: Strøm L1
      unit_of_measurement: A
      value_template: "{{ state_attr('sensor.real_time_consumption_norumvegen_17', 'currentPhase1')}}"
      icon_template: mdi:current-ac

    nv17_a_l2:
      friendly_name: Strøm L2
      unit_of_measurement: A
      value_template: "{{ state_attr('sensor.real_time_consumption_norumvegen_17', 'currentPhase2')}}"
      icon_template: mdi:current-ac

    nv17_a_l3:
      friendly_name: Strøm L3
      unit_of_measurement: A
      value_template: "{{ state_attr('sensor.real_time_consumption_norumvegen_17', 'currentPhase3')}}"
      icon_template: mdi:current-ac