- platform: waze_travel_time
  origin: !secret home_address
  destination: !secret knut_work_address
  name: 'Til Swisslog'
  region: 'EU'
  
- platform: waze_travel_time
  origin: !secret home_address
  destination: !secret simon_work_address
  name: 'Til Lørenskog VGS'
  region: 'EU'
  
- platform: waze_travel_time
  origin: !secret home_address
  destination: 'Edvard Munchs veg, 2061 Gardermoen'
  name: 'Til Gardermoen'
  region: 'EU'
  
