# - alias: "Activate evening scene"
#   trigger:
#     platform: state
#     entity_id: input_select.house_mode
#     to: 'Kveld'
#   action:
#     - service: script.turn_on
#       entity_id: script.kveldsmodus
      
- alias: "Activate night scene"
  trigger:
    platform: state
    entity_id: input_select.house_mode
    to: 'Natt'
  action:
    - service: script.turn_on
      entity_id: script.nattmodus
      
- alias: "Activate morning scene"
  trigger:
    platform: state
    entity_id: input_select.house_mode
    to: 'Dag'
  action:
    - service: script.turn_on
      entity_id: script.morgenmodus