- alias: Toggle bedroom ceiling light on single click
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/0x00158d000223b244'
  condition:
    condition: template
    value_template: "{{ 'single' == trigger.payload_json.click }}"
  action:
  - service: light.toggle
    entity_id: light.bedroom
      
- alias: Turn on bedroom nightstand light on double click
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/0x00158d000223b244'
  condition:
    - condition: template
      value_template: "{{ 'double' == trigger.payload_json.click }}"
    - condition: state
      entity_id: input_boolean.bed_light_toggle_memory
      state: 'off'
  action:
  - service: light.turn_on
    entity_id: light.bed_light
  - service: input_boolean.turn_on
    entity_id: input_boolean.bed_light_toggle_memory
    
- alias: Turn off bedroom nightstand light on double click
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/0x00158d000223b244'
  condition:
    - condition: template
      value_template: "{{ 'double' == trigger.payload_json.click }}"
    - condition: state
      entity_id: input_boolean.bed_light_toggle_memory
      state: 'on'
  action:
  - service: light.turn_off
    entity_id: light.bed_light
  - service: input_boolean.turn_off
    entity_id: input_boolean.bed_light_toggle_memory
    
- alias: Activate night mode on triple click
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/0x00158d000223b244'
  condition:
    condition: template
    value_template: "{{ 'triple' == trigger.payload_json.click }}"
  action:
  - service: scene.turn_on
    entity_id:
    - scene.nattmodus