- alias: Turn on outdoor lights when the sun sets
  trigger:
    platform: sun
    event: sunset
  action:
    service: light.turn_on
    entity_id: light.garage_outside
    
- alias: Turn off outdoor lights when the sun rises
  trigger:
    platform: sun
    event: sunrise
  action:
    service: light.turn_off
    entity_id: light.garage_outside