# Activate night mode on mon-thu + sunday
- alias: "House to night mode"
  trigger:
    platform: time
    at: '01:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - sun
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.house_mode
        option: Natt
    - service: notify.ios_knut_iphone
      data:
        message: "Nattmodus aktivert"

# Set house to evening mode
- alias: "House to evening mode"
  trigger:
    platform: time
    at: '23:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
        - sun
    - condition: state
      entity_id: binary_sensor.house_not_night_mode
      state: 'on'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.house_mode
        option: Kveld
    - service: notify.ios_knut_iphone
      data:
        message: "Kveldsmodus aktivert"


# Activate morning mode on weekdays
- alias: "House to morning mode weekday"
  trigger:
    platform: time
    at: '05:15:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.house_mode
        option: Dag
    - service: notify.ios_knut_iphone
      data:
        message: "Morgenmodus aktivert"

# Activate morning mode on weekends
- alias: "House to morning mode weekends"
  trigger:
    platform: time
    at: '08:00:00'
  condition:
    - condition: time
      weekday:
        - sat
        - sun
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.house_mode
        option: Dag
    - service: notify.knut
      data:
        message: "Morgenmodus aktivert"