- alias: Toggle lights kjøkkenbenk
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: 'smart_switch_kjokkenbenk'
      event: 1002
  action:
  - service: light.toggle
    entity_id: light.kjokkenbenk

- alias: Dim up lights kjøkkenbenk
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: 'smart_switch_kjokkenbenk'
      event: 2002
  action:
  - service: light.turn_on
    entity_id: light.kjokkenbenk
    data_template:
      brightness: >
          {% set suggested = states.light.kjokkenbenk.attributes.brightness|int + 50 %}
          {% if suggested < 255 %}
          {{ suggested }}
          {% else %}
          255
          {% endif %}

- alias: Dim down lights kjøkkenbenk
  trigger:
  - platform: event
    event_type: deconz_event
    event_data:
      id: 'smart_switch_kjokkenbenk'
      event: 3002
  action:
  - service: light.turn_on
    entity_id: light.kjokkenbenk
    data_template:
      brightness: >
          {% set suggested = states.light.kjokkenbenk.attributes.brightness|int - 50 %}
          {% if suggested > 25 %}
          {{ suggested }}
          {% else %}
          25
          {% endif %}