- alias: Dim valperom
  trigger:
    platform: mqtt
    topic: 'zigbee2mqtt/dimmer_valperom'
  action:
  - service: light.turn_on
    data_template:
      brightness: "{{ trigger.payload_json.brightness }}"
      entity_id: light.valperom
      
