########################################
#  BASEMENT
########################################

light:
  - platform: switch
    name: Kjeller gulvlampe
    entity_id: switch.kjeller_gulvlampe

  - platform: switch
    name: Kjeller lampett 1
    entity_id: switch.kjeller_lampett_1

  - platform: switch
    name: Kjeller lampett 2
    entity_id: switch.kjeller_lampett_2

  - platform: switch
    name: Kjeller lampett 3
    entity_id: switch.kjeller_lampett_3

  - platform: group
    name: Alt lys kjeller
    entities:
      - light.kjeller_gulvlampe
      - light.kjeller_lampett_1
      - light.kjeller_lampett_2
      - light.kjeller_lampett_3

timer:
  basement_light_turnoff:
    name: Time remaining
    duration: 600

automation:
  - id: basement_turn_off_light_delay
    alias: "Basement: Turn off light delay"
    trigger:
      - platform: state
        entity_id: binary_sensor.bevegelse_kjeller
        from: "on"
        to: "off"
    action:
      - service: timer.start
        data:
          entity_id: timer.basement_light_turnoff

  - id: basement_turn_off_light
    alias: "Basement: Turn off light"
    trigger:
      - platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.basement_light_turnoff
    action:
      - service: light.turn_off
        data:
          entity_id: light.alt_lys_kjeller

  - id: basement_turn_on_light
    alias: "Basement: Turn on light"
    trigger:
      - platform: state
        entity_id: binary_sensor.bevegelse_kjeller
        from: "off"
        to: "on"
      - platform: state
        entity_id: binary_sensor.bevegelse_kjeller_2
        from: "off"
        to: "on"
    action:
      - service: light.turn_on
        data:
          entity_id: light.alt_lys_kjeller
      - service: timer.cancel
        data:
          entity_id: timer.basement_light_turnoff

  - id: basement_deactivate_light_automation_kjellerstue
    alias: "Basement: Deactivate light automation kjellerstue"
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: "kjellerstue"
          event: 2001
    action:
      - service: automation.turn_off
        entity_id:
          - automation.basement_turn_on_light
          - automation.basement_turn_off_light
          - automation.basement_turn_off_light_delay

  - id: basement_activate_light_automation_kjellerstue
    alias: "Basement: Activate light automation kjellerstue"
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: "kjellerstue"
          event: 1001
      - platform: state
        entity_id: input_select.house_mode
        to: Kveld
        for: 30 min
    action:
      - service: automation.turn_on
        entity_id:
          - automation.basement_turn_on_light
          - automation.basement_turn_off_light
          - automation.basement_turn_off_light_delay

  - id: basement_turn_off_light_kjellerstue
    alias: "Basement: Turn off light"
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: "kjellerstue"
          event: 2002
    action:
      - service: light.turn_off
        entity_id:
          - light.alt_lys_kjeller

  - id: basement_turn_on_light_kjellerstue
    alias: "Basement: Turn on light"
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: "kjellerstue"
          event: 1002
    action:
      - service: light.turn_on
        entity_id:
          - light.alt_lys_kjeller
