########################################
#  BASEMENT
########################################

light:
  - platform: switch
    name: Kjeller gulvlampe
    entity_id: switch.kjeller_gulvlampe

  - platform: switch
    name: Kjeller lampett 1
    entity_id: switch.kjeller_lampett_1

  - platform: switch
    name: Kjeller lampett 2
    entity_id: switch.kjeller_lampett_2

  - platform: switch
    name: Kjeller lampett 3
    entity_id: switch.kjeller_lampett_3

  - platform: group
    name: Alt lys kjeller
    entities:
      - light.kjeller_gulvlampe
      - light.kjeller_lampett_1
      - light.kjeller_lampett_2
      - light.kjeller_lampett_3

automation:
  - id: basement_deactivate_light_automation_kjellerstue
    alias: "Basement: Deactivate light automation kjellerstue"
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: "kjellerstue"
          event: 2001
    action:
      - service: automation.turn_off
        entity_id:
          - automation.basement_lightsensor

  - id: basement_activate_light_automation_kjellerstue
    alias: "Basement: Activate light automation kjellerstue"
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: "kjellerstue"
          event: 1001
      - platform: state
        entity_id: input_select.house_mode
        to: Kveld
        for: 30 min
    action:
      - service: automation.turn_on
        entity_id:
          - automation.basement_lightsensor

  - id: basement_turn_off_light_kjellerstue
    alias: "Basement: Turn off light"
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: "kjellerstue"
          event: 2002
    action:
      - service: light.turn_off
        entity_id:
          - light.alt_lys_kjeller

  - id: basement_turn_on_light_kjellerstue
    alias: "Basement: Turn on light"
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: "kjellerstue"
          event: 1002
    action:
      - service: light.turn_on
        entity_id:
          - light.alt_lys_kjeller
