automation:
  - alias: "Bathroom: Turn on lights"
    trigger:
      platform: state
      entity_id: binary_sensor.bathroom_movement
      to: 'on'
    condition:
    - condition: numeric_state
      entity_id: sensor.bathroom_multisensor_luminance
      below: '600'
    action:
      - service: homeassistant.turn_on
        entity_id: switch.bathroom_ceiling_light
      # - service: notify.ios_knut_iphone
      #   data:
      #     message: "Baderomslys PÅ"
    
  - alias: "Bathroom: Turn off lights"
    trigger:
      platform: state
      entity_id: binary_sensor.bathroom_movement
      to: 'off'
      for:
        minutes: '5'
    action:
      - service: homeassistant.turn_off
        entity_id: switch.bathroom_ceiling_light
      # - service: notify.ios_knut_iphone
      #   data:
      #     message: "Baderomslys AV"

binary_sensor:
  - platform: template
    sensors:
      bathroom_movement:
        device_class: motion
        friendly_name: Bevegelse bad
        value_template: "{{ is_state('sensor.bathroom_multisensor_motion', '8') }}"