########################################
#  BEDROOM
########################################

input_boolean:
  bed_light_toggle_memory:
    name: Bed light toggle memory
    initial: off

light:
  - platform: group
    name: "Taklys soverom"
    entities:
      - light.taklys_soverom_1
      - light.taklys_soverom_2
  - platform: switch
    name: Nattbordslampe
    entity_id: switch.nattbordslampe

automation:
  - alias: "Bedroom: Toggle nightstand light on center click"
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: "taklys_soverom"
          event: 1002
    action:
      - service: light.toggle
        entity_id: light.nattbordslampe

  - alias: "Bedroom: Set house to night mode on triple click after 21"
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: "taklys_soverom"
          event: 5002
    condition:
      - condition: time
        after: "21:00:00"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.house_mode
          option: Natt

  - alias: "Bedroom: Activate night scene on triple click before 21"
    trigger:
      - platform: event
        event_type: deconz_event
        event_data:
          id: "taklys_soverom"
          event: 5002
    condition:
      - condition: time
        before: "21:00:00"
    action:
      - service: script.turn_on
        entity_id: script.nattmodus
