binary_sensor:
  - platform: mqtt
    name: ozw_network_ready
    state_topic: OpenZWave/1/status/
    value_template: >
      {{ "ON" if value_json.Status in ["driverAwakeNodesQueried", "driverAllNodesQueriedSomeDead", "driverAllNodesQueried"] else "OFF" }}
    json_attributes_topic: OpenZWave/1/status/
    device_class: "connectivity"

automation:
  # Start Homekit
  - alias: "Start HomeKit"
    trigger:
      - event: start
        platform: homeassistant
    action:
      - wait_template: "{{ is_state('binary_sensor.ozw_network_ready', 'on') }}"
        timeout: 00:10:00
      - service: homekit.start

homekit:
  name: HASS Bridge
  auto_start: false
  filter:
    include_entities:
      - light.stue
      - light.hund
      - light.taklys_soverom
      - light.nattbordslampe
      - light.garage_center
      - light.hagelys
      - light.taklys_bad
      - climate.kontor
