########################################
#  HOUSE MODE
########################################

input_select:
  house_mode:
    name: Husmodus
    options:
      - Morgen
      - Dag
      - Kveld
      - Natt
      - Bortreist
      - Gjestemodus
    initial: Dag
    icon: mdi:home

binary_sensor:
  - platform: workday
    name: Workday today
    country: 'NO'
  - platform: workday
    name: Workday tomorrow
    country: 'NO'
    days_offset: 1
  - platform: template
    sensors:
      house_not_night_mode:
        friendly_name: House is not in night mode
        value_template: "{{ not is_state('input_select.house_mode', 'Natt')}}"

script:
  ### Nattmodus
  nattmodus:
    sequence:
      - service: scene.turn_on
        entity_id: scene.nattmodus_off
      - delay: 0:00:01
      - service: scene.turn_on
        entity_id: scene.nattmodus_on
          
  ### Morgenmodus
  morgenmodus:
    sequence:
      - service: light.turn_on
        data:
          entity_id: light.taklys_gang, light.horus_2, light.trapp_1, light.taklys_kjokken
          brightness: 20
      - service: light.turn_on
        data:
          entity_id: light.kjokkenbenk, light.taklys_inngang
          brightness: 200
      
  kveldsmodus:
    sequence:
      - service: light.turn_on
        data:
          entity_id: light.stue
          brightness_pct: 50
          transition: 10

automation:
  # Morning mode at 05:15 on weekdays, else 08:00
  - alias: House mode to morning
    trigger:
      platform: template
      value_template: '{% if is_state("binary_sensor.workday_today", "on") and is_state("sensor.time", "05:15") or is_state("binary_sensor.workday_today", "off") and is_state("sensor.time", "08:00")-%}true{%- endif %}' 
    action:
      service: input_select.select_option
      data:
        entity_id: input_select.house_mode
        option: Morgen
  
  - alias: House mode to day
    trigger:
      platform: time
      at: '10:00'
    action:
      service: input_select.select_option
      data:
        entity_id: input_select.house_mode
        option: Dag

  - alias: House mode to evening
    trigger:
      platform: template
      value_template: '{% if is_state("binary_sensor.workday_tomorrow", "on") and is_state("sensor.time", "21:00") or is_state("binary_sensor.workday_tomorrow", "off") and is_state("sensor.time", "23:45")-%}true{%- endif %}' 
    action:
      service: input_select.select_option
      data:
        entity_id: input_select.house_mode
        option: Kveld

  - alias: House mode to night
    trigger:
      platform: time
      at: '02:00'
    condition:
      condition: state
      entity_id: input_select.house_mode
      state: "{{ not is_state(input_select.house_mode, 'Natt') }}"
    action:
      service: input_select.select_option
      data:
        entity_id: input_select.house_mode
        option: Kveld

  - alias: Notify changed housemode
    trigger:
      platform: state
      entity_id: input_select.house_mode
    action:
      service: notify.mobile_app_siphone
      data:
        message: "House set to {{ states('input_select.house_mode') }}"