
automation:
  - alias: "Kitchen: Toggle lights kjøkkenbenk"
    trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: 'smart_switch_kjokkenbenk'
        event: 1002
    action:
    - service: light.toggle
      entity_id: light.kjokkenbenk

  - alias: "Kitchen: Lights kjøkkenbenk to 100%"
    trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: 'smart_switch_kjokkenbenk'
        event: 2002
    action:
    - service: light.turn_on
      entity_id: light.kjokkenbenk
      data:
        brightness_pct: 100

  - alias: "Kitchen: Lights kjøkkenbenk to 75%"
    trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: 'smart_switch_kjokkenbenk'
        event: 5002
    action:
    - service: light.turn_on
      entity_id: light.kjokkenbenk
      data:
        brightness_pct: 75

  - alias: "Kitchen: Light kjøkkenbenk to 50%"
    trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: 'smart_switch_kjokkenbenk'
        event: 3002
    action:
    - service: light.turn_on
      entity_id: light.kjokkenbenk
      data:
        brightness_pct: 50

  - alias: "Kitchen: Light kjøkkenbenk to 25%"
    trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: 'smart_switch_kjokkenbenk'
        event: 4002
    action:
    - service: light.turn_on
      entity_id: light.kjokkenbenk
      data:
        brightness_pct: 25