########################################
### TABLET PACKAGE
########################################

### Control
rest_command:
  kiosk_command:
    url: !secret tablet_rest_url


light:
  - platform: template
    lights:
      tablet_backlight:
        friendly_name: Tablet Backlight
        value_template: '{{ states.sensor.kiosk_device_info.attributes["isScreenOn"] }}'
        level_template: '{{ states.sensor.kiosk_device_info.attributes["screenBrightness"] }}'
        turn_on:
          service: rest_command.kiosk_command
          data:
            cmd: screenOn
        turn_off:
          service: rest_command.kiosk_command
          data:
            cmd: screenOff
        set_level:
          service: rest_command.kiosk_command
          data_template:
            cmd: setStringSetting
            key: screenBrightness
            value: '{{ brightness }}'


### Automations
automation:
  - id: tablet_reduce_brightness_at_night
    alias: "Tablet: Reduce brightness at night"
    trigger:
      - platform: state
        entity_id: input_select.house_mode
        to: Kveld 
    action: 
      service: light.turn_on
      data_template: 
        entity_id: light.tablet_backlight
        brightness_pct: 20

  - id: tablet_increase_brightness_morning
    alias: "Tablet: Increase brightness in the morning"
    trigger:
      - platform: state
        entity_id: input_select.house_mode
        to: Morgen 
    action: 
      service: light.turn_on
      data_template: 
        entity_id: light.tablet_backlight
        brightness_pct: 80

  - id: tablet_stop_charging
    alias: "Tablet: Stop charging"
    trigger:
      - platform: numeric_state
        entity_id: sensor.tablet_rest
        value_template: "{{ state.attributes.batteryLevel }}"
        above: 99
    action:
      service: switch.turn_off
      entity_id: switch.tablet_power_switch

  - id: tablet_start_charging
    alias: "Tablet: Start charging"
    trigger:
      - platform: numeric_state
        entity_id: sensor.tablet_rest
        value_template: "{{ state.attributes.batteryLevel }}"
        below: 65
    action:
      service: switch.turn_on
      entity_id: switch.tablet_power_switch

### Sensors
sensor:
  - platform: rest
    name: tablet_rest
    json_attributes:
      - batteryLevel
      - kioskMode
      - screenBrightness
      - motionDetectorState
      - maintenanceMode
      - hostname4
      - ip4
      - mac
      - startUrl
      - currentPage
    resource: !secret tablet_rest_info_url
    value_template: '{{ value_json.batteryLevel }}'
